version: "3.8"

services:
  sweep:
    build:
      dockerfile: Dockerfile.gpu
  run:
    build:
      dockerfile: Dockerfile.gpu
    deploy:
      resources:
        reservations:
          devices:
            - device_ids: ["4", "5", "6", "7"]
              capabilities: [gpu]
