[tool.poetry]
name = "gqn"
version = "0.1.0"
description = ""
authors = ["Ethan Brooks <ethanabrooks@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
openai = "^0.16.0"
gym = "^0.23.1"
numpy = "^1.22.3"
altair = "^4.2.0"
GitPython = "^3.1.27"
dollar-lambda = {git = "https://github.com/ethanabrooks/dollar-lambda.git", rev = "main"}
sweep-logger = {git = "https://github.com/run-tracker/sweep-logger.git", rev = "main"}
vega-charts = {git = "https://github.com/run-tracker/vega-charts.git", rev = "main"}

[tool.poetry.dev-dependencies]
ipython = "^8.2.0"
ipdb = "^0.13.9"
black = "^22.3.0"
pre-commit = "^2.18.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
