env_id: chain
model_name: gpt2
failure_threshold: 0
gamma: 0.9
logprobs: 5
max_trajectory: 8
min_successes: 1
prompt_size: 8
success_buffer_size: 6
status: true
seed: 0
temperature: 0.1
top_p: 1
total_steps: 70
eval_interval: null
